mathematiciens = [["Legendre", "Adrien-Marie", "1752", "Paris", "1833", "Paris"],
                  ["Hilbert", "David ", "1862", "Königsberg", "1943", "Göttingen"],
                  ["Bernoulli", "Jakob", "1654", "Bâle", "1705", "Bâle"],
                  ["Cesàro", "Ernesto", "1859", "Naples", "1906", "Torre Annunziata"],
                  ["Euler", "Leonhard", "1707", "Bâle", "1783", " Saint-Pétersbourg"],
                  ["Bertrand", "Joseph", "1822", "Paris", "1900", "Paris"],
                  ["Stirling", "James ", "16920", "Garden", "1770", "Édimbourg"],
                  ["Wallis", "John ", "1616", "Ashford", "1703", "Oxford"],
                  ["Raabe", "Joseph Ludwig ", "1801", "Brody", "1859", "Zurich"],
                  ["Duhamel", "Jean-Marie", "1797", "Saint-Malo", "1872", "Paris"],
                  ["Abel", "Niels Henrik", "1802", "Finnøy", "1829", "Froland"],
                  ["Lagrange", "Joseph-Louis", "1736", "Turin", "1813", "Paris"],
                  ["Vandermonde", "Alexandre-Théophile", "1735", "Paris", "1796", "Paris"],
                  ["Tchebychev", "Pafnouti Lvovitch", "1821", "Borovsk", "1894", "Saint-Pétersbourg"],
                  ["Cauchy", "Augustin Louis", "1789", "Paris", "1857", "Sceaux"],
                  ["Lebesgue", "Henri-Léon", "1875", "Beauvais", "1941", "Paris"],
                  ["Riemann", "Bernhard", "1826", "Breselenz", "1866", "Selasca"],
                  ["Fourier", "Joseph", "1768", "Auxerre", "1830", "Paris"],
                  ["Dirichlet", "Johann Peter Gustav Lejeune", "1805", "Düren", "1859", "Göttingen"],
                  ["Gauss", "Carl Friedrich", "1777", "Brunswick", "1855", "Göttingen"],
                  ["Hölder", "Otto Ludwig", "1859", "Stuttgart", "1937", "Leipzig"],
                  ["Weierstrass", "Karl", "1815", "Ostenfelde", "1897", "Berlin"],
                  ["Bernstein", "Sergueï Natanovitch", "1880", "Odessa", "1968", "Moscou"],
                  ["Borel", "Émile", "1871", "Saint-Affrique", "1956", "Paris"],
                  ["Cantelli", "Francesco Paolo", "1875", "Palerme", "1966", "Rome"],
                  ["Wald", "Abraham", "1902", "Kolozsvár", "1950", "Travancore"],
                  ["Markov", "Andreï Andreïevitch", "1856", "Riazan", "1922", "Saint-Pétersbourg"],
                  ["Laplace", "Pierre-Simon de", "1749", "Beaumont-en-Auge", "1827", "Paris"],
                  ["Rolle", "Michel", "1652", "Ambert", "1719", "Paris"],
                  ["Cramer", "Gabriel", "1704", "Genève", "1752", "Bagnols-sur-Cèze"],
                  ["Iwasama", "Kenkichi", "1917", "Kiryū", "1998", "Tokyo"],
                  ["Laguerre", "Edmond", "1834", "Bar-le-Duc", "1886", "Bar-le-Duc"],
                  ["Gram", "Jørgen Pedersen", "1850", "Haderslev", "1916", "Copenhague"],
                  ["Chasles", "Michel", "1793", "Épernon", "1880", "Paris"],
                  ["Monge", "Gaspard", "1746", "Beaune", "1818", "Paris"],
                  ["Darboux", "Gaston", "1842", "Nîmes", "1917", "Paris"],
                  ["Stone", "Marshall Harvey", "1903", "New York City", "1989", "Madras"],
                  ["Hermite", "Charles", "1822", "Dieuze", "1901", "Paris"],
                  ["Bessel", "Friedrich Wilhelm", "1784", "Minden", "1846", "Königsberg"],
                  ["Wirtinger", "Wilhelm", "1865", "Ybbs an der Donau", "1945", "Ybbs an der Donau"],
                  ["Gronwall", "Thomas Hakon", "1877", "Dylta bruk", "1932", "New York City"],
                  ["König", "Johann Samuel", "1712", "Büdingen", "1757", "Zuilenstein"],
                  ["Huygens", "Christian", "1629", "La Haye", "1695", "La Haye"],
                  ["Pascal", "Blaise", "1623", "Clermont-Ferrand", "1662", "Paris"]
                  ]

mathematiciens.sort(key=lambda x: x[0])
for name in mathematiciens:
    print("\item " + "\\" + "textcolor{RoyalBlue}{" + "\\" + "textsc{" + name[0] + "}}" + " " + name[1] + " (" + name[3] + ", " + name[2] + " - " + name[5] + ", " + name[4] + ")")
